# Generated by Django 3.2.23 on 2024-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
